-- Mission150: run this in Supabase SQL Editor. Safe to run more than once.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  is_paid boolean not null default false,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile" on public.profiles for select to authenticated using (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin
  insert into public.profiles (id) values (new.id) on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create table if not exists public.payment_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null default 99,
  utr text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create unique index if not exists payment_requests_utr_unique on public.payment_requests(utr);
create index if not exists payment_requests_user_idx on public.payment_requests(user_id, created_at desc);

alter table public.payment_requests enable row level security;
drop policy if exists "Users can create their own payment requests" on public.payment_requests;
create policy "Users can create their own payment requests" on public.payment_requests for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users can read their own payment requests" on public.payment_requests;
create policy "Users can read their own payment requests" on public.payment_requests for select to authenticated using (auth.uid() = user_id);

-- After verifying a payment, approve it from Supabase SQL Editor:
-- update public.profiles set is_paid=true, paid_at=now() where id='USER_UUID';
-- update public.payment_requests set status='approved', reviewed_at=now() where id=REQUEST_ID;
